services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672"  # Management UI

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "changemaker"
      MONGO_INITDB_ROOT_PASSWORD: "makingchange2024"
      MONGO_INITDB_DATABASE: "secwatch"
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth  # Explicitly enable authentication

volumes:
  mongodb_data:
